apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  annotations:
    github.com/project-slug: ${{"coe-tech/" + values.app_name}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coe-tech
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner}}
